GET http://localhost:8080/posts

###
POST http://localhost:8080/posts/signup
Content-Type: application/json

{
    "firstName": "naza",
    "lastName": "amuche",
    "password": "okpalugo1@gmail.com",
    "email": "okpalugo1@gmail.com"
}

###
POST http://localhost:8080/posts/signin
Content-Type: application/json

{
    "email": "egbon@gmail.com",
    "password": "nonsownosunah@gmail.com"
}