GET http://localhost:8080/posts

###
POST http://localhost:8080/posts/signup
Content-Type: application/json

{
    "firstName": "naza",
    "lastName": "ioooo",
    "password": "okpalugo100@gmail.com",
    "email": "test3@gmail.com"
}

###
POST http://localhost:8080/posts/signin
Content-Type: application/json

{
    "email": "osi@gmail2224445657.com",
    "password": "okpalugo100@gmail.com"
}

###
GET http://localhost:8080/posts/details/6048c2c48f78df1813d03ac3