GET http://localhost:3000/posts

###
POST http://localhost:3000/posts/signup
Content-Type: application/json

{
    "firstName": "naza",
    "lastName": "amuche2",
    "password": "okpalugo100@gmail.com",
    "email": "okpalugo100@gmail.com"
}

###
POST http://localhost:3000/posts/signin
Content-Type: application/json

{
    "email": "egbon@gmail.com",
    "password": "nonsownosunah@gmail.com"
}